# Filtering

In [1]:
import pandas as pd

In [30]:
df = pd.read_csv('Data/survey_results_public.csv')
schema_df = pd.read_csv('Data/survey_results_schema.csv')
pd.set_option('display.max_columns',85)

In [31]:
df.head()

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,NaN,"Developer, mobile",20 to 99 employees,EUR European Euro,4800.0,Monthly,C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift,Swift,PostgreSQL;SQLite,SQLite,NaN,NaN,Laravel;Symfony,NaN,NaN,NaN,NaN,NaN,PHPStorm;Xcode,Atom;Xcode,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Multiple times per day,Yes,A few times per month or weekly,"Yes, definitely",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
1,2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,NaN,NaN,NaN,NaN,NaN,JavaScript;Python,NaN,PostgreSQL,NaN,NaN,NaN,Angular;Flask;Vue.js,NaN,Cordova,NaN,Docker;Git;Yarn,Git,Android Studio;IntelliJ;Notepad++;PyCharm,NaN,Windows,Visit Stack Overflow;Google it,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,"Yes, definitely",No,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
2,3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;C;Python;R;Rust,Julia;Python;Rust,SQLite,SQLite,Heroku,NaN,Flask,Flask,NumPy;Pandas;TensorFlow;Torch/PyTorch,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,NaN,NaN,IPython/Jupyter;PyCharm;RStudio;Sublime Text;V...,IPython/Jupyter;RStudio;Sublime Text;Visual St...,MacOS,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,"Yes, definitely",Yes,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
3,4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,NaN,"Developer, front-end",100 to 499 employees,EUR European Euro,NaN,Monthly,JavaScript;TypeScript,JavaScript;TypeScript,NaN,NaN,NaN,NaN,Angular;jQuery,Angular;jQuery,NaN,NaN,NaN,NaN,NaN,NaN,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,Neutral,No,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
4,5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,10,"Developer, desktop or enterprise applications;...","Just me - I am a freelancer, sole proprietor, ...",GBP\tPound sterling,NaN,NaN,Bash/Shell;HTML/CSS;Python;SQL,Bash/Shell;HTML/CSS;Python;SQL,Elasticsearch;PostgreSQL;Redis,Cassandra;Elasticsearch;PostgreSQL;Redis,NaN,NaN,Flask,Flask,Apache Spark;Hadoop;NumPy;Pandas,Hadoop;NumPy;Pandas,Docker;Git;Kubernetes;Yarn,Docker;Git;Kubernetes;Yarn,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim;Vis...,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per week,"Yes, somewhat",No,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN

In [32]:
schema_df.head()

,qid,qname,question,force_resp,type,selector
0,QID16,S0,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
1,QID12,MetaInfo,Browser Meta Info,False,Meta,Browser
2,QID1,S1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
3,QID2,MainBranch,Which of the following options best describes ...,True,MC,SAVR
4,QID24,Employment,Which of the following best describes your cur...,False,MC,MAVR

In [46]:
IndiaCountry_filt = ( (df['Country'] == "India") & (df['Employment'] == "Student, full-time") )

In [47]:
df.loc[IndiaCountry_filt , ['Employment' , 'Gender'] ]

               Employment                                             Gender
22     Student, full-time                                                Man
49     Student, full-time                                                Man
59     Student, full-time  Non-binary, genderqueer, or gender non-conforming
189    Student, full-time                                                Man
230    Student, full-time                                                Man
...                   ...                                                ...
83135  Student, full-time                                                Man
83171  Student, full-time                                                Man
83209  Student, full-time                                                Man
83406  Student, full-time                                                Man
83417  Student, full-time                                                Man

[2229 rows x 2 columns]

In [48]:
Countries = ["India" , "Netherlands"]
filt = df['Country'].isin(Countries)

In [50]:
df.loc[filt]

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
1,2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,NaN,NaN,NaN,NaN,NaN,JavaScript;Python,NaN,PostgreSQL,NaN,NaN,NaN,Angular;Flask;Vue.js,NaN,Cordova,NaN,Docker;Git;Yarn,Git,Android Studio;IntelliJ;Notepad++;PyCharm,NaN,Windows,Visit Stack Overflow;Google it,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,"Yes, definitely",No,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
8,9,I am a developer by profession,Employed part-time,India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,Coding Bootcamp,6,4,"Developer, front-end","10,000 or more employees",INR\tIndian rupee,NaN,Monthly,HTML/CSS;JavaScript,HTML/CSS;JavaScript,PostgreSQL,PostgreSQL,AWS,NaN,Django;FastAPI,Django;FastAPI,NaN,NaN,Docker;Git,Docker;Git;Kubernetes,PyCharm;Sublime Text,PyCharm;Sublime Text,Windows,Visit Stack Overflow;Google it;Panic,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,"Yes, definitely",No,25-34 years old,Man,No,NaN,South Asian,NaN,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,NaN
22,23,I am a student who is learning to code,"Student, full-time",India,NaN,NaN,Some college/university study without earning ...,5 - 10 years,School;Friend or family member,7,NaN,NaN,NaN,NaN,NaN,NaN,C#;HTML/CSS;Python,Java;Kotlin;Python,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unity 3D,NaN,Android Studio,Android Studio,Windows,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,"Yes, definitely",No,Under 18 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
39,40,I am a student who is learning to code,"Student, part-time",India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,School,3,NaN,NaN,NaN,NaN,NaN,NaN,C;C#;C++;HTML/CSS;JavaScript;Node.js;Python,NaN,MongoDB,NaN,Heroku,NaN,Express;jQuery;React.js,NaN,Keras;NumPy;TensorFlow,NaN,Flow;Unity 3D,NaN,IPython/Jupyter;Sublime Text;Visual Studio Code,NaN,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,A few times per month or weekly,"Yes, somewhat",Yes,18-24 years old,Woman,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,NaN
49,50,I am a student who is learning to code,"Student, full-time",India,NaN,NaN,Some college/university study without earning ...,11 - 17 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C;HTML/CSS;Java;JavaScript;Kotlin;Node.js;Pyth...,Dart;Elixir;Go;SQL,NaN,NaN,Heroku,NaN,Django;Express;React.js,Angular,NaN,NaN,Git;Yarn,NaN,Android Studio;Atom;Notepad++;Sublime Text;Vis...,NaN,Windows,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow,Multiple times per day,Yes,A few times per week,"Yes, definitely",No,18-24 years old,Man,No,Straight / Heterosexual,South Asian,None of the above,None of the above,Appropriate in length,Easy,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83406,83407,I am a student who is learning to code,"Student, full-time",India,NaN,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",2,NaN,NaN,NaN,NaN,NaN,NaN,C;C++;Python,C;C#;C++;HTML/CSS;JavaScript;Python;Rust;SQL;T...,MySQL,MySQL;Oracle,NaN,NaN,NaN,NaN,NumPy,.NET Framework;Flutter;NumPy;React Native;Tens...,Git,Deno;Docker;Git,PyCharm;Visual Studio Code,NaN,Windows,Visit Stack Overflow;Google it;Do other work a...,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,I have never participated in Q&A on Stack Over...,"No, not really",Yes,18-24 years old,Man,No,Straight / Heterosexual,South Asian,None of the above,None of the above,Appropriate in length,Easy,NaN
83409,83410,I am a developer by profession,Employed full-time,Netherlands,NaN,NaN,"Other doctoral degree (Ph.D., Ed.D., etc.)",18 - 24 years,School,12,6,"Developer, desktop or enterprise applications;...","10,000 or more employees",EUR European Euro,80000.0,Yearly,Julia;Matlab;Python,Julia,MySQL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Git,Docker;Git,IPython/Jupyter;Notepad++;Visual Studio Code,IPython/Jupyter;Notepad++;Visual Studio Code,Windows,Call a coworker or friend;Go for a walk or oth...,Stack Overflow,A few times per week,No,NaN,"No, not really",Yes,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,86478.0
83410,83411,I am a student who is learning to code,"Student, part-time",India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,"Other online resources (ex: videos, blogs, etc)",1,NaN,NaN,NaN,NaN,NaN,NaN,C++;JavaScript;Python;TypeScript,C++;JavaScript;Python;TypeScript,MongoDB;PostgreSQL;SQLite,MongoDB;PostgreSQL;SQLite,Heroku,Heroku,Express;React.js,Express;React.js,Keras;NumPy;TensorFlow,Keras;NumPy;TensorFlow,Docker;Git;Unreal Engine,Docker;Git;Unreal Engine,Android Studio;Atom;Eclipse;IntelliJ;IPython/J...,IPython/Jupyter;PyCharm;Vim;Visual Studio;Visu...,Windows,Google it;Panic,Stack Overflow;Stack Exchange,Multiple times per day,Yes,I have never participated in Q&A on Stack Over...,"Yes, definitely",No,18-24 years old,Man,No,Straight / Heterosexual,I don't know,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,NaN
83411,83412,I am a developer by profession,Employed full-time,India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",8,5,"Developer, back-end",100 to 499 employees,INR\tIndian rupee,3500000.0,Yearly,Java;JavaScript;SQL,Go;Java;Kotlin;Node.js;SQL,MySQL,Cassandra;Elasticsearch;Redis,AWS,AWS;Google Cloud Platform,Spring,Spring,NaN,NaN,Docker;Git,Ansible;Docker;Git;Kubernetes;Terraform,Eclipse;Sublime Text;Visual Studio Code,Eclipse;IntelliJ;Sublime Text,MacOS,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange;Stack Overflow f...,Daily or almost daily,Yes,Less than once per month or monthly,"Yes, somewhat",No,25-34 years old,Man,No,Straight / Heterosexual,South Asian,None of the above,None of the above,Appropriate in length,Easy,48866.0
83417,83418,I am a developer by profession,"Student, full-time",India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,School;Friend or family member;Online Courses ...,3,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell;C;C++;Java;SQL,Bash/Shell;C++;SQL,PostgreSQL;SQLite,PostgreSQL,AWS,Google Cloud Platform;Microsoft Azure,Spring,jQuery;Spring,NaN,NaN,Docker;Git,Docker;Git,IntelliJ;Vim;Visual Studio Code,IntelliJ;Vim;Visual Studio Code,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange;Stack Overflow f...,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",Yes,18-24 years old,Man,No,NaN,South Asian,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN